apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: initium-cli
rules:
  - apiGroups:
      - ''
      - serving.knative.dev
      - apps
      - networking.k8s.io
    resources:
      - namespaces
      - deployments
      - replicasets
      - ingresses
      - services
      - secrets
      - configmaps
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch