FROM node:{{ or .RuntimeVersion .DefaultRuntimeVersion }} AS build-env
COPY . /src
WORKDIR /src
RUN npm i
RUN npm run build --if-present
RUN npm test

FROM gcr.io/distroless/nodejs20-debian11
COPY --from=build-env /src /src
WORKDIR /src
CMD ["index.js"]
