FROM node:{{ or .RuntimeVersion .DefaultRuntimeVersion }} AS build-env

WORKDIR /app

COPY package*.json tsconfig*.json ./

RUN {{ .NodeInstallCommand }}

COPY . /app

RUN npm run build --if-present
RUN npm test

FROM gcr.io/distroless/nodejs20-debian11
COPY --from=build-env /app /app
WORKDIR /app
USER nonroot

CMD ["index.js"]