FROM node:{{ or .RuntimeVersion .DefaultRuntimeVersion }} AS build-env

WORKDIR /app

COPY package*.json tsconfig*.json ./

RUN {{ .NodeInstallCommand }}

COPY . .

RUN npm run build --if-present
RUN npm test

FROM node:{{ or .RuntimeVersion .DefaultRuntimeVersion }}

COPY --from=build-env /app /app

WORKDIR /app

EXPOSE 3000

USER node

CMD npx http-server -p 3000 ./build
