name: Deploy on main

on: 
  push:
    branches:
      - main

jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.GO_VERSION }}

      - name: build and deploy on main
        run: go run main.go onmain --stop-on-push
        env:
          INITIUM_APP_NAME: initium-cli
          INITIUM_REGISTRY_USER: ${{ github.actor }}
          INITIUM_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}