name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v4
        with:
          go-version: stable

      - uses: goreleaser/goreleaser-action@v4
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        # This sets up the .npmrc file for publishing to npm
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - run: |
          cd npm
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm ci
          otp=(curl -s \
            -d '{ "packageInfo": { "version": "$(cat package.json | jq -r '.version')", "name": "$(cat package.json | jq -r '.name')" } }' \
            -H "Content-Type: application/json" \
            -X POST \
            ${{ secrets.OPTIC_URL }}${{ secrets.OPTIC_TOKEN }})
          npm publish --otp ${otp}
